import {sharingParties,organizationLinks} from './parties.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function compactMap(s){
 const parties=sharingParties(s),links=organizationLinks(s);
 const coords={'OWNER-DEMO-mesh':[[170,112],[170,244]],'OWNER-DEMO-pcn':[[210,112],[210,144],[830,144],[830,244]],'RECIPIENT-DEMO-mesh':[[500,112],[500,188],[205,188],[205,244]],'OSAT-DEMO-pcn':[[870,112],[870,244]]};
 const paths=links.map(l=>{const points=[...coords[l.id]];if(l.direction==='from-service')points.reverse();return `<path data-org-link="${l.id}" data-direction="${l.direction??'idle'}" class="org-wire ${l.direction?'link-transferring':''}" d="${points.map((p,i)=>(i?'L':'M')+p.join(' ')).join(' ')}" stroke="${l.service==='mesh'?'#43D39E':'#62B5FF'}" marker-end="url(#${l.service}-tip)" fill="none"><title>${esc(l.organization)} ↔ ${l.service}: ${esc(l.label)}</title></path>`;}).join('');
 const nodes=parties.map((p,i)=>{const x=40+i*330;return `<g class="map-org" data-party="${p.id}" role="button" tabindex="0" aria-label="Inspect ${esc(p.name)}"><rect x="${x}" y="20" width="260" height="92" rx="10" class="${p.active?'party-active':''}"/><text x="${x+14}" y="46" class="map-name">${esc(p.name)}</text><text x="${x+14}" y="69">${p.connections.map(c=>c==='mesh'?'Hushmesh':'PCN').join(' + ')} · fictional</text><text x="${x+14}" y="92">${p.active?'Active in this step':'Select for role and permissions'}</text></g>`;}).join('');
 const services=[['mesh','Hushmesh','Apps & identities','Owner-controlled data',40],['adapter','Proposed bridge','Identity · mapping · permission','A failed check stops sharing',370],['pcn','PCN','Data Objects & history','Originals stay with the owner',700]].map(([id,title,line,sub,x])=>`<g data-block="${id}" role="button" tabindex="0" aria-label="Inspect ${title}" class="map-service"><rect x="${x}" y="244" width="260" height="98" rx="10"/><text class="map-name" x="${x+14}" y="272">${title}</text><text x="${x+14}" y="297">${line}</text><text x="${x+14}" y="320">${sub}</text></g>`).join('');
 const lanes=[['mesh-in','M300 276H362'],['mesh-out','M630 276H692'],['pcn-in','M700 311H638'],['pcn-out','M370 311H308'],['receipt-mesh','M830 344V365H170V344'],['receipt-pcn','M170 344V390H830V344']].map(([id,d])=>`<path data-lane="${id}" d="${d}" fill="none" stroke="${id.includes('mesh')?'#43D39E':'#62B5FF'}" stroke-width="2" marker-end="url(#${id.includes('mesh')?'mesh':'pcn'}-tip)"/>`).join('');
 const mobile=parties.map(p=>`<button data-party="${p.id}"><strong>${esc(p.name)}</strong><span>${p.connections.map(c=>c==='mesh'?'Hushmesh':'PCN').join(' + ')}</span></button>`).join('')+links.map(l=>`<div class="mobile-map-link ${l.direction?'link-transferring':''}"><span>${esc(l.organization)}</span><b>${l.direction==='from-service'?'←':'→'}</b><span>${l.service==='mesh'?'Hushmesh':'PCN'}</span><small>${esc(l.label)}</small></div>`).join('')+`<button data-block="adapter">Proposed bridge · checks each exchange</button><div class="mobile-service-buttons"><button data-block="mesh">Hushmesh</button><button data-block="pcn">PCN</button></div>`;
 return `<svg class="compact-map" viewBox="0 0 1000 410" role="group" aria-label="Aster connects to both services, Northstar to Hushmesh, and Harbor to PCN. The proposed bridge connects the services."><defs>${['mesh','pcn'].map(c=>`<marker id="${c}-tip" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="${c==='mesh'?'#43D39E':'#62B5FF'}"/></marker>`).join('')}</defs>${paths}${nodes}${services}${lanes}<text x="340" y="166" class="link-caption">Aster’s PCN connection</text><text x="275" y="210" class="link-caption">Northstar’s Hushmesh connection</text></svg><div class="compact-mobile">${mobile}</div>`;
}
