const entries=[
 ['Identity','OIDC + OAuth','Real integration profile to confirm','Identity owner','Identify a caller and authorize resource calls. A real browser connector would need an agreed secure flow, such as Authorization Code with PKCE. Sign-in is not permission to disclose data.','https://openid.net/specs/openid-connect-core-1_0.html','OIDC Core','https://www.rfc-editor.org/rfc/rfc9700.html','OAuth Security BCP'],
 ['Identity','JWT / JOSE / JWK','Required if signed tokens are used','Security owner','Validate signature, algorithm, issuer, audience, expiry and transaction binding. A decoded token alone is not verified identity. ID tokens and access tokens serve different purposes.','https://www.rfc-editor.org/rfc/rfc8725.html','JWT Security BCP'],
 ['Messages','TLS 1.3','Secure transport required for a real bridge','Platform owner','Protect traffic between approved endpoints. Encryption does not tell you whether the business data is true or whether a recipient is allowed to receive it.','https://www.rfc-editor.org/rfc/rfc8446.html','TLS 1.3'],
 ['Messages','JSON Schema 2020-12','Selected simulator contract','Adapter owner','Check message shape and required fields. Separate rules still check tenant mapping, purpose, recipient, asset and field scope.','https://json-schema.org/draft/2020-12','JSON Schema'],
 ['Messages','OpenAPI + CloudEvents','Optional future profiles','Adapter owner','Document partner-approved HTTP interfaces and event metadata. Neither format solves permission, message ordering or duplicate effects on its own.','https://spec.openapis.org/oas/','OpenAPI','https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md','CloudEvents 1.0.2'],
 ['Trust','RATS + EAT','Conceptual candidates only','Security reviewer','Separate trust evidence, a verifier’s appraisal and the relying party’s decision. The stale-evidence failure is simulated; it does not establish Hushmesh support for these standards.','https://www.rfc-editor.org/rfc/rfc9334.html','RATS','https://www.rfc-editor.org/rfc/rfc9711.html','EAT'],
 ['Trust','Verifiable Credentials + DIDs','Optional future extension','Credential / identity owner','Portable claims require an agreed issuer, verifier and identifier method. The proof-only PCN scenario is not automatically a W3C credential.','https://www.w3.org/TR/vc-data-model-2.0/','VC 2.0','https://www.w3.org/TR/did-core/','DID Core'],
 ['History','GS1 EPCIS','Optional supply-chain profile','PCN data owner','Use a common language for product events if the use case needs it. This simulator’s fictional observation is not a validated EPCIS event.','https://ref.gs1.org/standards/epcis/2.0.1/','EPCIS 2.0.1'],
 ['Permissions','PCN registration & disclosure','PCN-specific; deployment status to confirm','Data owner + PCN protocol owner','DPP, SDP, SDA and Qualified Storage are PCN concepts described in the supplied wiki. They are not general industry standards. This lab models their purpose; real APIs and enforcement need partner confirmation.']
];
export const standardsHTML=`<div class="standards-grid">${entries.map(([group,name,status,owner,description,url,label,url2,label2])=>`<article class="card"><div class="eyebrow">${group}</div><h3>${name}</h3><span class="badge">${status}</span><p>${description}</p><small>Responsible: ${owner}</small>${url?`<p><a href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>${url2?` · <a href="${url2}" target="_blank" rel="noopener noreferrer">${label2} ↗</a>`:''}</p>`:'<p>Source: supplied PCN wiki, pages 356–369. Private source files are not bundled.</p>'}</article>`).join('')}</div>
<section class="requirements"><h3>Critical technical requirements</h3><p>Keep three decisions separate: whether the approved agent software is running, whether the requested action is permitted, and whether the business result is acceptable. A passed execution check does not prove that outside data is true.</p><ol><li>Map the trusted issuer and subject to a reviewed actor, tenant, asset and public Mesh alias. Never exchange Stem IDs or private keys.</li><li>Recheck recipient, asset, purpose, fields, expiry and revocation immediately before delivery—even after a retry.</li><li>Keep original files under owner control. Whether Mesh can qualify as PCN storage requires an explicit assessment.</li><li>Bind each payload to its reviewed revision and source context. Identity and a matching digest cannot prove a sensor reading is true.</li><li>Use stable operation IDs, bounded retries, per-asset ordering and authoritative reconciliation. Do not promise exactly-once network delivery.</li><li>Distinguish delivery receipt, committed record, authorized endorsement and evaluation result. Each means something different.</li><li>Keep audit history minimal. Agree on retention, withdrawal and downstream use with both partners.</li><li>Public browser assets cannot hold secrets. Real connectors need a separately designed trusted service.</li></ol></section>
<section class="requirements"><h3>Plain-language glossary</h3><dl class="glossary"><div><dt>PIN</dt><dd>A PCN identifier for an asset, not a secret password.</dd></div><div><dt>DPP</dt><dd>PCN registration protocol: model an asset’s record and history.</dd></div><div><dt>SDA</dt><dd>A disclosure agreement that limits who may receive what and why.</dd></div><div><dt>SDP</dt><dd>PCN disclosure protocol: model sharing under an agreement.</dd></div><div><dt>Qualified Storage</dt><dd>Owner-controlled storage that must meet PCN requirements; Mesh qualification is unconfirmed.</dd></div><div><dt>Endorsement</dt><dd>An authorized party’s statement about a record. A delivery receipt is not an endorsement.</dd></div></dl></section>
<section class="requirements"><h3>Questions for the integration partners</h3><p>Confirm current Mesh data APIs, OIDC grants and key rotation; the public alias-to-subject mapping; PCN deployed protocol versions; receipt and retention semantics; storage qualification; attestation evidence and freshness; and who can endorse, revoke or reconcile.</p><p><a href="https://github.com/hushmesh/mesh-sample-oidc-app" target="_blank" rel="noopener noreferrer">Hushmesh OIDC sample ↗</a> supplies sample-level identity integration information. Its omitted browser signature verification must not be copied into a real connector.</p><p>This lab uses supplied PCN wiki definitions and Hushmesh technical material reviewed for the spec-kit plan. “Documented” describes the source concept, “proposed” describes the bridge, and “simulated” describes every running check here.</p></section>`;
